### ISSUE TITLE
`output`-based exercise

### ISSUE THREAD

**Issue by jrvidal** [fmoko/rustlings#270]
I've been wondering whether it'd be useful to have a 3rd kind of exercise, `"output"`/`Mode::Output`, that compares the stdout of an exercise to an expected value before moving on to the next one. This would imply a minor re-invention the `#[test]` framework, since we'd need to produce our own `Expected`/`Actual` output and stuff. 

However, I feel that it would be a good fit for some `println`-based exercises, where the user can simply manipulate the program until it generates the desired output in a way that feels more natural to me than using `#[test]`. For instance, a hypothetical 0-exercise with an empty `main()` that expects you to print "Hello world". Or some of the `if`-based exercises, where the user can test branches until the correct one is executed. In fact, I suspect it'd be a good fit for most of the exercises for which we get complaints about them passing too soon.

@fmoko What do you think? If that sounds OK I'd be glad to send a patch.

**Comment by fmoko** [comment]
@jrvidal That sounds good! It's probably a good replacement for `#[test]`-based exercises, except for the ones that teach you about `#[test]`.
