### ISSUE TITLE
Primitive_type5 doesn't check the result

### ISSUE THREAD

**Issue by sinan-314** [fmoko/rustlings#286]
the result isn't checked, so the result can be `3.5 is 3.5 years old.` instead of `Furry McFurson is 3.5 years old`. the first result have been checked and passed the test. so just compare the output and no just see if the programe compile.

**Comment by jrvidal** [comment]
https://github.com/fmoko/rustlings/pull/278 will slightly improve this (and other exercises that pass without actually testing anything) by giving you a chance to inspect the input before moving on.
