### ISSUE TITLE
`rustlings run` does not work with clippy exercises

### ISSUE THREAD

**Issue by jrvidal** [fmoko/rustlings#291]
```
⠚ Compiling exercises/clippy/clippy1.rs...
thread 'main' panicked at 'Failed to run 'run' command: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/exercise.rs:134:19
```

The issue is in `exercise::Exercise::compile`, where we assume that the executable is in `temp_file()`, but the clippy compilation does not actually build there.

**Comment by crodjer** [comment]
@jrvidal I'd like to take fixing this up. It'd be a learning experience for me.
