### ISSUE TITLE
rustlings run resets Cargo.toml (clippy1)

### ISSUE THREAD

**Issue by jhscheer** [fmoko/rustlings#300]
I solved `clippy1.rs` by using `float_cmp::approx_eq`, however I cannot finish this exercise because during `rustlings run clippy1` the `Cargo.toml` resets and deletes the new dependency I added.
```
[dependencies]
float-cmp = "0.6.0"
```

**Comment by sjmann** [comment]
I think that you may have arrived at a correct, but unintended answer to this exercise. Have you checked the hint from clippy which appears against the code before you modify it?

I think this exercise could be probably be improved by adding an extra line to the header comment explaining what to do (maybe something like: `fix this code by following clippy's advice`)

**Comment by jhscheer** [comment]
> I think that you may have arrived at a correct, but unintended answer to this exercise. Have you checked the hint from clippy which appears against the code before you modify it?
> 
Now I did, thanks.
> I think this exercise could be probably be improved by adding an extra line to the header comment explaining what to do (maybe something like: `fix this code by following clippy's advice`)
>
Probably yes.
