### ISSUE TITLE
meta-thread for me to use the all-contributors bot to add everyone to it

### ISSUE THREAD

**Issue by fmoko** [fmoko/rustlings#302]
I want to add https://allcontributors.org/ support, but their bot doesn't support any kind of bulk add so I have to @ people who've previously contributed explicitly here. If you get mentioned here, take it as a special thanks from me to you to help make this piece of software a bit better!

**Comment by fmoko** [comment]
@all-contributors add @carols10cents for code and content

**Comment by fmoko** [comment]
@all-contributors add @QuietMisdreavus for code and content

**Comment by fmoko** [comment]
@all-contributors add @robertlugg for content

**Comment by fmoko** [comment]
@all-contributors add @hynek for code

**Comment by fmoko** [comment]
@all-contributors add @spacekookie for code

**Comment by fmoko** [comment]
@all-contributors add @lukabavdaz for code and content

**Comment by fmoko** [comment]
@all-contributors add @evestera for code

**Comment by fmoko** [comment]
@all-contributors add @Delet0r for code

**Comment by fmoko** [comment]
@all-contributors add @shaunbennett for code

**Comment by fmoko** [comment]
@all-contributors add @abagshaw for code

**Comment by fmoko** [comment]
@all-contributors add @kisom for code

**Comment by fmoko** [comment]
@all-contributors add @ColinPitrat for code

**Comment by fmoko** [comment]
@all-contributors add @zacanger for code

**Comment by fmoko** [comment]
@all-contributors add @mgeier for code

**Comment by fmoko** [comment]
@all-contributors add @cjpearce for code

**Comment by fmoko** [comment]
@all-contributors add @yvan-sraka for code

**Comment by fmoko** [comment]
@all-contributors add @dendi239 for code

**Comment by fmoko** [comment]
@all-contributors add @eddyp for code

**Comment by fmoko** [comment]
@all-contributors add @briankung for code and content

**Comment by fmoko** [comment]
@all-contributors add @miller-time for code

**Comment by fmoko** [comment]
@all-contributors add @danwilhelm for docs

**Comment by fmoko** [comment]
@all-contributors add @Jesse-Cameron for code and content

**Comment by fmoko** [comment]
@all-contributors add @MrFroop for code

**Comment by fmoko** [comment]
@all-contributors add @petemcfarlane for content

**Comment by fmoko** [comment]
@all-contributors add @nkanderson for code and content

**Comment by fmoko** [comment]
@all-contributors add @ajaxm for docs

**Comment by fmoko** [comment]
@all-contributors add @Dylnuge for content

**Comment by fmoko** [comment]
@all-contributors add @vyaslav for code and content

**Comment by fmoko** [comment]
@all-contributors add @gdoenlen for code

**Comment by fmoko** [comment]
@all-contributors add @nyxtom for code and content

**Comment by fmoko** [comment]
@all-contributors add @workingjubilee for code

**Comment by fmoko** [comment]
@all-contributors add @WofWca for code

**Comment by fmoko** [comment]
@all-contributors add @jrvidal for code and docs and ideas and maintenance

**Comment by fmoko** [comment]
@all-contributors add @jensim for docs

**Comment by fmoko** [comment]
@all-contributors add @rahatarmanahmed for docs

**Comment by fmoko** [comment]
@all-contributors add @AbdouSeck for code and content and review

**Comment by fmoko** [comment]
@all-contributors add @Socratides for docs

**Comment by fmoko** [comment]
@all-contributors add @codehearts for code

**Comment by fmoko** [comment]
@all-contributors add @codehearts for code

(previous one conflicted)

**Comment by fmoko** [comment]
@all-contributors add @gnodarse for content

**Comment by fmoko** [comment]
@all-contributors add @harrisonmetz for code

**Comment by fmoko** [comment]
@all-contributors add @TorbenJ for code and content

**Comment by fmoko** [comment]
@all-contributors add @pbx for docs

**Comment by fmoko** [comment]
@all-contributors add @sjmann for code and content

**Comment by fmoko** [comment]
@all-contributors add @Tarnadas for code and content

**Comment by fmoko** [comment]
@all-contributors add @sl4m for code

**Comment by fmoko** [comment]
@all-contributors add @sanjaykdragon for code and content

**Comment by fmoko** [comment]
@all-contributors add @crodjer for code

**Comment by fmoko** [comment]
That's it for now! I think I have most people, but if I skipped you for whatever reason and you contributed to this project before, feel free to make a new issue or send me an email about it and I'll add you!

**Comment by rahatarmanahmed** [comment]
Thank you!

**Comment by crodjer** [comment]
Thanks!

**Comment by AbdouSeck** [comment]
Thank you!
